# Generated by Django 4.2.27 on 2025-12-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstep',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
