# Generated by Django 4.2.27 on 2025-12-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('keywords', models.JSONField(default=list)),
                ('actionable_steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_readiness_score', models.IntegerField(default=0)),
                ('market_percentile', models.IntegerField(default=0)),
                ('projected_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('opportunities', models.JSONField(default=list)),
                ('threats', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('pricing_current', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pricing_recommended', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pricing_reasoning', models.TextField(blank=True)),
                ('portfolio_score', models.IntegerField(default=0)),
                ('github_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('tech_stack_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
