# Generated by Django 4.2.27 on 2025-12-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='availability_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='session_duration',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
