# Generated by Django 4.2.27 on 2025-12-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('review', 'Needs Review')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyntheticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('skills', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('github_repos', models.IntegerField(default=0)),
                ('github_stars', models.IntegerField(default=0)),
                ('portfolio_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(default='generated', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('breakdown', models.JSONField(default=dict)),
                ('llm_rationale', models.TextField(blank=True)),
                ('improvements', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('flagged_for_human', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='agents.ingestionjob')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cv', 'CV/Resume'), ('github', 'GitHub'), ('portfolio', 'Portfolio'), ('linkedin', 'LinkedIn Public'), ('blog', 'Blog/Medium'), ('form', 'Form Input')], max_length=50)),
                ('raw_content', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='agents.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(max_length=100)),
                ('percentiles', models.JSONField(default=dict)),
                ('avg_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_experience_years', models.FloatField(default=0)),
                ('common_skills', models.JSONField(default=list)),
                ('sample_size', models.IntegerField(default=0)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'skill_category')},
            },
        ),
    ]
