# Generated by Django 4.2.27 on 2025-12-02 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('market_trend', 'Market Trend'), ('skill_gap', 'Skill Gap'), ('career_advice', 'Career Advice'), ('learning_path', 'Learning Path'), ('salary_insight', 'Salary Insight'), ('project_suggestion', 'Project Suggestion')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('relevance_score', models.FloatField(default=0.8)),
                ('is_read', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='agents.ingestionjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'insight_type'], name='agents_aiin_user_id_800bbd_idx'), models.Index(fields=['user', 'is_read'], name='agents_aiin_user_id_76dde4_idx')],
            },
        ),
    ]
