# Generated by Django 4.2.27 on 2025-12-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_aiinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(choices=[('market_trend', 'Market Trend'), ('skill_gap', 'Skill Gap'), ('career_advice', 'Career Advice'), ('learning_path', 'Learning Path'), ('salary_insight', 'Salary Insight'), ('project_suggestion', 'Project Suggestion'), ('swot_analysis', 'SWOT Analysis'), ('salary_comparison', 'Salary Comparison'), ('skill_demand', 'Skill Demand')], max_length=30),
        ),
    ]
