# Generated by Django 4.2.27 on 2025-12-04 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0003_alter_aiinsight_insight_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('agents_executed', models.IntegerField(default=0)),
                ('agents_succeeded', models.IntegerField(default=0)),
                ('agents_failed', models.IntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
                ('results', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_executions', to='agents.ingestionjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_evaluation', models.JSONField(default=dict)),
                ('decision', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('human_confidence', models.FloatField(blank=True, null=True)),
                ('accuracy_rating', models.IntegerField(blank=True, null=True)),
                ('relevance_rating', models.IntegerField(blank=True, null=True)),
                ('actionability_rating', models.IntegerField(blank=True, null=True)),
                ('modified_strengths', models.JSONField(blank=True, null=True)),
                ('modified_weaknesses', models.JSONField(blank=True, null=True)),
                ('modified_recommendations', models.JSONField(blank=True, null=True)),
                ('modified_score', models.FloatField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('disagreement_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='agents.ingestionjob')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('score_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_reviews', to='agents.scoresnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentWeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(default=dict)),
                ('previous_weights', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=dict)),
                ('trigger', models.CharField(max_length=100)),
                ('reviews_analyzed', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('execution_time', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('error', models.TextField(blank=True, null=True)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id', 'created_at'], name='agents_agen_agent_i_9ef4c6_idx'), models.Index(fields=['agent_id', 'success'], name='agents_agen_agent_i_6e2c23_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=100)),
                ('context_hash', models.CharField(db_index=True, max_length=32)),
                ('context', models.JSONField(default=dict)),
                ('decision', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id', 'context_hash'], name='agents_agen_agent_i_1cd072_idx'), models.Index(fields=['agent_id', 'outcome'], name='agents_agen_agent_i_46d401_idx'), models.Index(fields=['created_at'], name='agents_agen_created_fc6de8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('agent_id', models.CharField(db_index=True, max_length=100)),
                ('job_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=1)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='agents_agen_event_t_8de5a4_idx'), models.Index(fields=['job_id', 'created_at'], name='agents_agen_job_id_5d5999_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('metric', models.CharField(max_length=100)),
                ('current_value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id', 'severity'], name='agents_agen_agent_i_2924e8_idx'), models.Index(fields=['acknowledged', 'created_at'], name='agents_agen_acknowl_b9978f_idx')],
            },
        ),
    ]
